### ISSUE TITLE
fully containerized builds and orchestration

### ISSUE THREAD

**Issue by simevo** [ISAITB/gitb#19]
If you wish to make it easier for people that want to try out this product, you may want to supply a `docker-compose.yml` file that orchestrates all services. The TL;DR section of the README would be:

> just launch `docker-compose up` and visit [http://localhost:9000](http://localhost:9000)

ATM information about how to start the containers one by one is in [/etc/docker](/ISAITB/gitb/tree/master/etc/docker), but before building the images one has to launch `mvn install ...` for `gitb-srv` (to generate `itbsrv.war`) and `sbt compile && npm run build` for `gitb-ui` (to generate the `gitb` binary) beforehand.

Fully containerized builds = `docker-compose build` can perform all these steps without preinstalling the tools (maven, java jdk, sbt, nodejs, npm) and the required Java and JavaScript libraries.

**Comment by costas80** [comment]
Thanks for the feedback @simevo ! We actually have extensive documentation on how to use the GITB Test Bed software as part of our online guides, specifically:
* The [development installation guide](https://www.itb.ec.europa.eu/docs/guides/latest/installingTheTestBed/index.html), which covers exactly what you highlight using docker-compose or simple docker commands.
* The [production installation guide](https://www.itb.ec.europa.eu/docs/guides/latest/installingTheTestBedProduction/index.html) which similarly uses docker-compose but goes into many more details regarding aspects such as security and reverse proxies.

Overall our documentation hub is on the European Commission's Joinup platform (see the Test Bed's space [here](https://joinup.ec.europa.eu/collection/interoperability-test-bed-repository/solution/interoperability-test-bed)) where we have a [dedicated page for all documentation](https://joinup.ec.europa.eu/collection/interoperability-test-bed-repository/solution/interoperability-test-bed/documentation-and-resources) (user guides, developer guides, references, tutorials etc.).

Having said this, you are absolutely right that all this is not reflected in this repository's README. We will add a relevant section here to point to the documentation so that the software's build and installation becomes obvious. We haven't included this up to now because the approach we foresee for reusing the Test Bed is via its published Docker images (see e.g. for [gitb-ui](https://hub.docker.com/r/isaitb/gitb-ui)), not by cloning and building it from source.

I hope this answers your point and in any case thanks for the tip to extend the README's documentation (will we do this asap).

**Comment by simevo** [comment]
Thanks for the quick reaction! The modified README is very helpful for people in a hurry that don't click through all the links and don't read all the docs (like me).

What is still missing is information how you built the images referenced by the `docker-compose.yml`, for example if I am curious which version of `maven` was used to build https://hub.docker.com/r/isaitb/gitb-srv, I am left clueless because I can't find the `Dockerfile` that was used to builld that.

**Comment by costas80** [comment]
Good to see the README update comes across clearly :)

Regarding your point on the tools used and the images' Dockerfiles, these are included in [/etc/docker](https://github.com/ISAITB/gitb/tree/master/etc/docker). We could add a section in the README to highlight this or as you initially suggested add an extra `docker-compose.yml` that can be used to make the build (and refer to that in the README). The reason we didn't do so is because most people use the images (via the installation guides) without checking this repo and adding an extra docker-compose.yml here might be confusing.

Nonetheless, from your earlier comment I assume you'd find the `docker-compose build` approach more useful right?

**Comment by simevo** [comment]
OK but the `Dockerfile`s in `/etc/docker` are not complete, for example this line: https://github.com/ISAITB/gitb/blob/master/etc/docker/gitb-srv/Dockerfile#L4 requires the file `itbsrv.war` to be present in the context (typically the current dir when you launch `docker build ...`). As documented, it's been prebuilt!

What is missing is a full containerized build, comprehensive of the steps required to generate this file `itbsrv.war` and the rest of the binaries. You have the procedure somewhere because you use it to build & publish the images on docker hub ...

**Comment by costas80** [comment]
Fair point. Indeed we have a script on our CI server that handles the hidden steps (do the mvn/sbt builds, and then copy needed resources plus Dockerfiles in temp folders before building the images). I agree with you that this could be improved by making a fully containerised build (for our own processes but also for documentation).

We'll work on the update asap. Thanks again for the suggestion!

**Comment by costas80** [comment]
Containerised builds have now been added to allow building and running without manual steps or installations (apart from installing Docker Compose). You may now use the included [docker-compose.yml](https://github.com/ISAITB/gitb/blob/master/docker-compose.yml) definition by issuing:
```
docker compose up -d --build
```
We also updated the [README](https://github.com/ISAITB/gitb#readme) to highlight this additional option and better document the previous one (installing all tools, building step by step, and carrying out certain manual actions). The original approach has been kept as it is much faster if you're actually developing and adapting the sources (not just experimenting).

@simevo , I assume this update covers what you were requesting. Can you confirm?

**Comment by costas80** [comment]
Closing this issue as containerised builds are now supported. The approach is documented in the repo's [README](https://github.com/ISAITB/gitb#build-using-docker-compose).
