### ISSUE TITLE
ITB make fail the test because Link header is empty

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#52]
Hello !

I want to test the behaviour of my SUT (a context broker) when the Link header is provided and empty.

All the steps are passed, however ITB points this empty Link header and fails the test.

<img width="269" alt="image" src="https://github.com/ISAITB/gitb/assets/143092948/615fbbed-2fa9-4c85-9cb5-d7861493a8e4">
<img width="423" alt="image" src="https://github.com/ISAITB/gitb/assets/143092948/0983e5d6-1d86-4fdd-9ace-34fb3319ddc8">

Here is a the testSuite :
[example.zip](https://github.com/ISAITB/gitb/files/15186096/example.zip)

**Comment by costas80** [comment]
I believe the problem comes from...
```
<assign to="headers{Link}"></assign>
```
... which should work if set as...
```
<assign to="headers{Link}">""</assign>
```
The content of the `assign` step is expected to be an XPath expression so it should not be completely empty. Also, I'd suggest you set the `<steps>` element as `<steps stopOnError="true">` so that the test session stops on errors rather than continue. Finally, if trying to pinpoint the location of a problem in a non-visible step you could use the [log step](https://www.itb.ec.europa.eu/docs/tdl/latest/constructs/index.html#log) to debug.

Does this help resolve the issue?

**Comment by EliottPaillard** [comment]
Yes the problem comes from this assign tag. 
But I wanted to test what my SUT responds when the Link header is "empty" exactly.
I also tried with the "" configuration but I was thinking to provide nothing was the good way to do it.
In fact it was not.
Thanks for your help
