### ISSUE TITLE
REST API Create Specification

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/gitb#68]
Hello @costas80,

I think it's not possible for now to create specification in the Domain management with the REST API.

To explain a bit, we have hundreds of testsuites and we would want one specification for each one.
It also raises the question of how ITB would display so many elements.
I believe the best now would be to sort them manually (or create them in a certain order) but I was wondering if allow the user to search by the first letter of the element could be a thing or not?

**Comment by costas80** [comment]
Hi @EliottPaillard. Indeed specifications can't be created via the REST API. In general the purpose (currently) of the REST API is not to create domains/specifications/groups/communities/organisations/systems. It is meant to work with an existing setup (with the exception of fully managing test suites). Having said this we will be adding simple CRUD operations for the next release as we are having several requests for it.

> To explain a bit, we have hundreds of testsuites and we would want one specification for each one.

This seems quite a stretch for the Test Bed's specification concept and I'm wondering if your test design is correct. Do you expect users to make individual conformance statements for all these specifications?

> I was wondering if allow the user to search by the first letter of the element could be a thing or not?

Users (both administrators and regular users) can already search for conformance statements by name. This applies both when creating a conformance statement and also when viewing your conformance status. Did you have something else in mind?

**Comment by EliottPaillard** [comment]
In fact, we expect the users to make a conformance statements with only a few specification of their choice.
We have let's say 100 data models (1 JSON schema for each of them) and for instance a user that want to test like 3 models he use.
I was trying to let a user create a system "MODEL" and create a conformance statement by selecting only the specification they want (1 data model to test being 1 specification)

I don't really know if it's the best solution.
I also tried to find a way to make all these things in only one test case.
Ideally this could be done with a interact, the user would select the models to test and for each one a pop-up would appear for the user to provide a JSON document

**Comment by costas80** [comment]
Ok I see. That makes sense.

> Ideally this could be done with a interact, the user would select the models to test and for each one a pop-up would appear for the user to provide a JSON document

I would advise against this, at least if you're interested in the conformance results. If the user can change each time what they are testing against then the fact that one test session was successful and another failed cannot be used to determine a consistent conformance status. If on the other hand your goal is more to provide this as a utility to users that's fine and you could use an `interact` (with the options presented in a dropdown).

**Comment by EliottPaillard** [comment]
I agree with you. 
From my point of view, the first option would be the best.
But this would require to create all the specification manually right?

**Comment by costas80** [comment]
Currently yes. Note that we are going to add REST API CRUD operations for additional concepts (including specifications) so you would be able to script it also. Once this is available I'll let you know.

**Comment by costas80** [comment]
Hi @EliottPaillard. The new REST API operations are now available to use through the nightly image. This doesn't cover only specifications we were discussing, but also all other elements linked to domains (domains, groups, specifications, actors), communities (communities, organisations, systems), and configuration property definitions (domain parameters, organisation properties, system properties, statement/actor properties).

The new operations are not publicly documented yet (this will be done as part of the next release), but you can already access the full OpenAPI/Swagger documentation as described [here](https://www.itb.ec.europa.eu/docs/itb-ta/latest/api/index.html#openapi-documentation). In brief, get the latest nightly build and load the API definition in a (separate) Swagger UI instance.

Don't hesitate to share feedback about the new API operations in case you miss anything.

**Comment by EliottPaillard** [comment]
Hi @costas80,
I took a look at the swagger. 
I didn't find how to create a domain specification.
Is it possible now?

**Comment by EliottPaillard** [comment]
Oh, I was wondering but yes I didn't see the last version of the swagger

**Comment by costas80** [comment]
Ok. So please do have a look and let me know if anything is unclear. Once you're happy with the new API operations we could also close the issue.

**Comment by EliottPaillard** [comment]
Hey @costas80,

I tried some new operations.
It's possible to update domain although I didn't succeed to create a new one.
Of course API request is enabled in my ITB settings, and also for the target Community.

Here is the form of my request:
curl --header "ITB_API_KEY: ******************************" -iX PUT 'http://localhost:9000/api/rest/domain' \
    --header "content-type: application/json" \
    --data-raw '{"shortName":"test","fullName":"est"}'

And the response I got:
{"error_code":"403","error_description":"You are not allowed to perform system-level operations through the automation API"}

**Comment by costas80** [comment]
Ah yes. You can do almost all operations with a community API key, the same way as you can manage almost anything when connecting on the UI as a community administrator. There are only a few exceptions that require a higher level of authentication:
* Creating a domain
* Deleting a domain.
* Creating a community.
* Deleting a community.

For these operations, you will need to use a different API key as the `ITB_API_KEY` header which is the master/admin API key. This is set for you at startup when you install a new Test Bed instance. To see it:
1. Connect as the Test Bed administrator (e.g. using account `admin@itb` if you haven't replaced it).
2. Go to the **System administration** menu.
3. See the API key to use under the **REST API** section.

![image](https://github.com/user-attachments/assets/5d7b9951-596e-4a2c-8220-ae0ff52b2353)

Note that for all other operations you must still use the community API key for authentication. This is because this API key serves also as the means of retrieving the relevant community/domain under which we are making the operation.

Can you confirm if this works for you?

**Comment by EliottPaillard** [comment]
It does!
Thank you for this clarification.

I continue to test the new operations I needed

**Comment by EliottPaillard** [comment]
Sorry I need you again...

To create a new specification, I need to provide the Domain Key but I didn't find how to.
Should it be as a header, in the endpoint, or in the body maybe?

**Comment by costas80** [comment]
Good catch! That was missing in the OpenAPI documentation (it will be there in the next nightly build). The domain API key is added in the payload as part of the specification's data: 

![image](https://github.com/user-attachments/assets/fc0fae4f-9449-4cb9-9090-99988a8d1303)

However this is only needed if the `ITB_API_KEY` (set with a community's API key) refers to a community that is not linked to a specific domain. Otherwise you can skip it, and the domain will be the one linked to the community.

**Comment by EliottPaillard** [comment]
I managed to do what I had in mind, I did not test each new operations but it went well so far
